name: CI
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  FORCE_COLOR: "1"

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: Test and Package
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        target: ["Ubuntu", "Fedora", "Windows"]
        include:
          - target: "Ubuntu"
            platform: "Linux"
            output-format: "system"
            runs-on: "ubuntu-latest"
            pre-command: |
              sudo apt-get update --fix-missing
              sudo apt-get install -y \
                socat libcairo2-dev libgirepository1.0-dev gir1.2-gtk-3.0 \
                libcanberra-gtk3-module build-essential git uuid-dev libblkid-dev libmount-dev
            briefcase-run-prefix: "xvfb-run"
            briefcase-args: "--target ubuntu"

          - target: "Fedora"
            platform: "Linux"
            output-format: "system"
            runs-on: "fedora-latest"
            pre-command: |
              sudo dnf install -y \
                socat cairo-devel gobject-introspection gtk3-devel \
                libcanberra-gtk3-devel make automake gcc gcc-c++ git util-linux-user
            briefcase-run-prefix: "xvfb-run"
            briefcase-args: "--target fedora"

          - target: "Windows"
            platform: "Windows"
            output-format: "system"
            runs-on: "windows-latest"
            pre-command: |
              echo "No pre-command needed for Windows"
            briefcase-run-prefix: ""
            briefcase-args: "--target windows"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Briefcase and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install briefcase==0.3.26

      - name: Setup Environment
        run: ${{ matrix.pre-command }}

      - name: Build App
        run: |
          ${{ matrix.briefcase-run-prefix }} \
          briefcase build \
            ${{ matrix.platform || matrix.target }} \
            ${{ matrix.output-format }} \
            ${{ matrix.briefcase-args }}

      - name: Package App
        run: |
          briefcase package \
            ${{ matrix.platform || matrix.target }} \
            ${{ matrix.output-format }} \
            --update --no-input --log \
            ${{ matrix.briefcase-args }}

      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: InsightWallet-${{ matrix.target }}
          path: dist
          if-no-files-found: warn
